# Generated by Django 4.1.3 on 2022-12-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipestep"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipestep",
            old_name="instructions",
            new_name="instruction",
        ),
    ]
